version: "3"
services:
  mongodb:
    image: mongo:5.0
    container_name: curriculum-backend-mongodb-queries-practice-mongodb-1
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb_data:
